---
title: MMDR Documentation
description: Minecraft Mod Development Runtime - Revolutionary development tools for mod developers
baseurl: "/MMDR"
url: "https://arlit1-f.github.io"
repository: arlit1-f/MMDR

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

nav:
  - title: Home
    url: /
  - title: Getting Started
    url: /guides/getting-started
  - title: Guides
    url: /guides/
    #subnav:
  - title: Hot Reload
    url: /guides/hot-reload
  - title: Console
    url: /guides/console
  - title: Inspector
    url: /guides/inspector
  - title: API Reference
    url: /guides/api-reference
  - title: GitHub
    url: https://github.com/ArliT1-F/MMDR
    external: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache

highlighter: rouge
permalink: pretty